hico_text_label = {
    (5, 5): "a photo of a person boarding an airplane",
    (18, 5): "a photo of a person directing an airplane",
    (26, 5): "a photo of a person exiting an airplane",
    (31, 5): "a photo of a person flying an airplane",
    (42, 5): "a photo of a person inspecting an airplane",
    (53, 5): "a photo of a person loading an airplane",
    (77, 5): "a photo of a person riding an airplane",
    (88, 5): "a photo of a person sitting on an airplane",
    (112, 5): "a photo of a person washing an airplane",
    (58, 5): "a photo of a person and an airplane",
    (9, 2): "a photo of a person carrying a bicycle",
    (37, 2): "a photo of a person holding a bicycle",
    (42, 2): "a photo of a person inspecting a bicycle",
    (44, 2): "a photo of a person jumping a bicycle",
    (38, 2): "a photo of a person hopping on a bicycle",
    (63, 2): "a photo of a person parking a bicycle",
    (72, 2): "a photo of a person pushing a bicycle",
    (76, 2): "a photo of a person repairing a bicycle",
    (77, 2): "a photo of a person riding a bicycle",
    (88, 2): "a photo of a person sitting on a bicycle",
    (99, 2): "a photo of a person straddling a bicycle",
    (111, 2): "a photo of a person walking a bicycle",
    (112, 2): "a photo of a person washing a bicycle",
    (58, 2): "a photo of a person and a bicycle",
    (11, 16): "a photo of a person chasing a bird",
    (27, 16): "a photo of a person feeding a bird",
    (37, 16): "a photo of a person holding a bird",
    (66, 16): "a photo of a person petting a bird",
    (75, 16): "a photo of a person releasing a bird",
    (113, 16): "a photo of a person watching a bird",
    (58, 16): "a photo of a person and a bird",
    (5, 9): "a photo of a person boarding a boat",
    (22, 9): "a photo of a person driving a boat",
    (26, 9): "a photo of a person exiting a boat",
    (42, 9): "a photo of a person inspecting a boat",
    (44, 9): "a photo of a person jumping a boat",
    (48, 9): "a photo of a person launching a boat",
    (76, 9): "a photo of a person repairing a boat",
    (77, 9): "a photo of a person riding a boat",
    (78, 9): "a photo of a person rowing a boat",
    (80, 9): "a photo of a person sailing a boat",
    (88, 9): "a photo of a person sitting on a boat",
    (94, 9): "a photo of a person standing on a boat",
    (106, 9): "a photo of a person tying a boat",
    (112, 9): "a photo of a person washing a boat",
    (58, 9): "a photo of a person and a boat",
    (9, 44): "a photo of a person carrying a bottle",
    (21, 44): "a photo of a person drinking with a bottle",
    (37, 44): "a photo of a person holding a bottle",
    (42, 44): "a photo of a person inspecting a bottle",
    (49, 44): "a photo of a person licking a bottle",
    (59, 44): "a photo of a person opening a bottle",
    (70, 44): "a photo of a person pouring a bottle",
    (58, 44): "a photo of a person and a bottle",
    (5, 6): "a photo of a person boarding a bus",
    (18, 6): "a photo of a person directing a bus",
    (22, 6): "a photo of a person driving a bus",
    (26, 6): "a photo of a person exiting a bus",
    (42, 6): "a photo of a person inspecting a bus",
    (53, 6): "a photo of a person loading a bus",
    (77, 6): "a photo of a person riding a bus",
    (88, 6): "a photo of a person sitting on a bus",
    (112, 6): "a photo of a person washing a bus",
    (114, 6): "a photo of a person waving a bus",
    (58, 6): "a photo of a person and a bus",
    (5, 3): "a photo of a person boarding a car",
    (18, 3): "a photo of a person directing a car",
    (22, 3): "a photo of a person driving a car",
    (39, 3): "a photo of a person hosing a car",
    (42, 3): "a photo of a person inspecting a car",
    (44, 3): "a photo of a person jumping a car",
    (53, 3): "a photo of a person loading a car",
    (63, 3): "a photo of a person parking a car",
    (77, 3): "a photo of a person riding a car",
    (112, 3): "a photo of a person washing a car",
    (58, 3): "a photo of a person and a car",
    (23, 17): "a photo of a person drying a cat",
    (27, 17): "a photo of a person feeding a cat",
    (37, 17): "a photo of a person holding a cat",
    (40, 17): "a photo of a person hugging a cat",
    (46, 17): "a photo of a person kissing a cat",
    (66, 17): "a photo of a person petting a cat",
    (81, 17): "a photo of a person scratching a cat",
    (112, 17): "a photo of a person washing a cat",
    (11, 17): "a photo of a person chasing a cat",
    (58, 17): "a photo of a person and a cat",
    (9, 62): "a photo of a person carrying a chair",
    (37, 62): "a photo of a person holding a chair",
    (50, 62): "a photo of a person lying on a chair",
    (88, 62): "a photo of a person sitting on a chair",
    (94, 62): "a photo of a person standing on a chair",
    (58, 62): "a photo of a person and a chair",
    (9, 63): "a photo of a person carrying a couch",
    (50, 63): "a photo of a person lying on a couch",
    (88, 63): "a photo of a person sitting on a couch",
    (58, 63): "a photo of a person and a couch",
    (27, 21): "a photo of a person feeding a cow",
    (35, 21): "a photo of a person herding a cow",
    (37, 21): "a photo of a person holding a cow",
    (40, 21): "a photo of a person hugging a cow",
    (46, 21): "a photo of a person kissing a cow",
    (47, 21): "a photo of a person lassoing a cow",
    (56, 21): "a photo of a person milking a cow",
    (66, 21): "a photo of a person petting a cow",
    (77, 21): "a photo of a person riding a cow",
    (111, 21): "a photo of a person walking a cow",
    (58, 21): "a photo of a person and a cow",
    (13, 67): "a photo of a person cleaning a dining table",
    (25, 67): "a photo of a person eating at a dining table",
    (87, 67): "a photo of a person sitting at a dining table",
    (58, 67): "a photo of a person and a dining table",
    (9, 18): "a photo of a person carrying a dog",
    (23, 18): "a photo of a person drying a dog",
    (27, 18): "a photo of a person feeding a dog",
    (34, 18): "a photo of a person grooming a dog",
    (37, 18): "a photo of a person holding a dog",
    (39, 18): "a photo of a person hosing a dog",
    (40, 18): "a photo of a person hugging a dog",
    (42, 18): "a photo of a person inspecting a dog",
    (46, 18): "a photo of a person kissing a dog",
    (66, 18): "a photo of a person petting a dog",
    (79, 18): "a photo of a person running a dog",
    (81, 18): "a photo of a person scratching a dog",
    (99, 18): "a photo of a person straddling a dog",
    (108, 18): "a photo of a person training a dog",
    (111, 18): "a photo of a person walking a dog",
    (112, 18): "a photo of a person washing a dog",
    (11, 18): "a photo of a person chasing a dog",
    (58, 18): "a photo of a person and a dog",
    (27, 19): "a photo of a person feeding a horse",
    (34, 19): "a photo of a person grooming a horse",
    (37, 19): "a photo of a person holding a horse",
    (40, 19): "a photo of a person hugging a horse",
    (44, 19): "a photo of a person jumping a horse",
    (46, 19): "a photo of a person kissing a horse",
    (53, 19): "a photo of a person loading a horse",
    (38, 19): "a photo of a person hopping on a horse",
    (66, 19): "a photo of a person petting a horse",
    (73, 19): "a photo of a person racing a horse",
    (77, 19): "a photo of a person riding a horse",
    (79, 19): "a photo of a person running a horse",
    (99, 19): "a photo of a person straddling a horse",
    (108, 19): "a photo of a person training a horse",
    (111, 19): "a photo of a person walking a horse",
    (112, 19): "a photo of a person washing a horse",
    (58, 19): "a photo of a person and a horse",
    (37, 4): "a photo of a person holding a motorcycle",
    (42, 4): "a photo of a person inspecting a motorcycle",
    (44, 4): "a photo of a person jumping a motorcycle",
    (38, 4): "a photo of a person hopping on a motorcycle",
    (63, 4): "a photo of a person parking a motorcycle",
    (72, 4): "a photo of a person pushing a motorcycle",
    (73, 4): "a photo of a person racing a motorcycle",
    (77, 4): "a photo of a person riding a motorcycle",
    (88, 4): "a photo of a person sitting on a motorcycle",
    (99, 4): "a photo of a person straddling a motorcycle",
    (109, 4): "a photo of a person turning a motorcycle",
    (111, 4): "a photo of a person walking a motorcycle",
    (112, 4): "a photo of a person washing a motorcycle",
    (58, 4): "a photo of a person and a motorcycle",
    (9, 1): "a photo of a person carrying a person",
    (32, 1): "a photo of a person greeting a person",
    (37, 1): "a photo of a person holding a person",
    (40, 1): "a photo of a person hugging a person",
    (46, 1): "a photo of a person kissing a person",
    (93, 1): "a photo of a person stabbing a person",
    (101, 1): "a photo of a person tagging a person",
    (103, 1): "a photo of a person teaching a person",
    (49, 1): "a photo of a person licking a person",
    (58, 1): "a photo of a person and a person",
    (9, 64): "a photo of a person carrying a potted plant",
    (37, 64): "a photo of a person holding a potted plant",
    (39, 64): "a photo of a person hosing a potted plant",
    (58, 64): "a photo of a person and a potted plant",
    (9, 20): "a photo of a person carrying a sheep",
    (27, 20): "a photo of a person feeding a sheep",
    (35, 20): "a photo of a person herding a sheep",
    (37, 20): "a photo of a person holding a sheep",
    (40, 20): "a photo of a person hugging a sheep",
    (46, 20): "a photo of a person kissing a sheep",
    (66, 20): "a photo of a person petting a sheep",
    (77, 20): "a photo of a person riding a sheep",
    (84, 20): "a photo of a person shearing a sheep",
    (111, 20): "a photo of a person walking a sheep",
    (112, 20): "a photo of a person washing a sheep",
    (58, 20): "a photo of a person and a sheep",
    (5, 7): "a photo of a person boarding a train",
    (22, 7): "a photo of a person driving a train",
    (26, 7): "a photo of a person exiting a train",
    (53, 7): "a photo of a person loading a train",
    (77, 7): "a photo of a person riding a train",
    (88, 7): "a photo of a person sitting on a train",
    (112, 7): "a photo of a person washing a train",
    (58, 7): "a photo of a person and a train",
    (14, 72): "a photo of a person controlling a tv",
    (76, 72): "a photo of a person repairing a tv",
    (113, 72): "a photo of a person watching a tv",
    (58, 72): "a photo of a person and a tv",
    (8, 53): "a photo of a person buying an apple",
    (16, 53): "a photo of a person cutting an apple",
    (24, 53): "a photo of a person eating an apple",
    (37, 53): "a photo of a person holding an apple",
    (42, 53): "a photo of a person inspecting an apple",
    (65, 53): "a photo of a person peeling an apple",
    (67, 53): "a photo of a person picking an apple",
    (90, 53): "a photo of a person smelling an apple",
    (112, 53): "a photo of a person washing an apple",
    (58, 53): "a photo of a person and an apple",
    (9, 27): "a photo of a person carrying a backpack",
    (37, 27): "a photo of a person holding a backpack",
    (42, 27): "a photo of a person inspecting a backpack",
    (59, 27): "a photo of a person opening a backpack",
    (115, 27): "a photo of a person wearing a backpack",
    (58, 27): "a photo of a person and a backpack",
    (8, 52): "a photo of a person buying a banana",
    (9, 52): "a photo of a person carrying a banana",
    (16, 52): "a photo of a person cutting a banana",
    (24, 52): "a photo of a person eating a banana",
    (37, 52): "a photo of a person holding a banana",
    (42, 52): "a photo of a person inspecting a banana",
    (65, 52): "a photo of a person peeling a banana",
    (67, 52): "a photo of a person picking a banana",
    (90, 52): "a photo of a person smelling a banana",
    (58, 52): "a photo of a person and a banana",
    (6, 39): "a photo of a person breaking a baseball bat",
    (9, 39): "a photo of a person carrying a baseball bat",
    (37, 39): "a photo of a person holding a baseball bat",
    (85, 39): "a photo of a person signing a baseball bat",
    (100, 39): "a photo of a person swinging a baseball bat",
    (105, 39): "a photo of a person throwing a baseball bat",
    (116, 39): "a photo of a person wielding a baseball bat",
    (58, 39): "a photo of a person and a baseball bat",
    (37, 40): "a photo of a person holding a baseball glove",
    (115, 40): "a photo of a person wearing a baseball glove",
    (58, 40): "a photo of a person and a baseball glove",
    (27, 23): "a photo of a person feeding a bear",
    (41, 23): "a photo of a person hunting a bear",
    (113, 23): "a photo of a person watching a bear",
    (58, 23): "a photo of a person and a bear",
    (13, 65): "a photo of a person cleaning a bed",
    (50, 65): "a photo of a person lying on a bed",
    (88, 65): "a photo of a person sitting on a bed",
    (58, 65): "a photo of a person and a bed",
    (42, 15): "a photo of a person inspecting a bench",
    (50, 15): "a photo of a person lying on a bench",
    (88, 15): "a photo of a person sitting on a bench",
    (58, 15): "a photo of a person and a bench",
    (9, 84): "a photo of a person carrying a book",
    (37, 84): "a photo of a person holding a book",
    (59, 84): "a photo of a person opening a book",
    (74, 84): "a photo of a person reading a book",
    (58, 84): "a photo of a person and a book",
    (37, 51): "a photo of a person holding a bowl",
    (97, 51): "a photo of a person stirring a bowl",
    (112, 51): "a photo of a person washing a bowl",
    (49, 51): "a photo of a person licking a bowl",
    (58, 51): "a photo of a person and a bowl",
    (16, 56): "a photo of a person cutting a broccoli",
    (24, 56): "a photo of a person eating a broccoli",
    (37, 56): "a photo of a person holding a broccoli",
    (90, 56): "a photo of a person smelling a broccoli",
    (97, 56): "a photo of a person stirring a broccoli",
    (112, 56): "a photo of a person washing a broccoli",
    (58, 56): "a photo of a person and a broccoli",
    (4, 61): "a photo of a person blowing a cake",
    (9, 61): "a photo of a person carrying a cake",
    (16, 61): "a photo of a person cutting a cake",
    (24, 61): "a photo of a person eating a cake",
    (37, 61): "a photo of a person holding a cake",
    (52, 61): "a photo of a person lighting a cake",
    (55, 61): "a photo of a person making a cake",
    (68, 61): "a photo of a person picking up a cake",
    (58, 61): "a photo of a person and a cake",
    (9, 57): "a photo of a person carrying a carrot",
    (15, 57): "a photo of a person cooking a carrot",
    (16, 57): "a photo of a person cutting a carrot",
    (24, 57): "a photo of a person eating a carrot",
    (37, 57): "a photo of a person holding a carrot",
    (65, 57): "a photo of a person peeling a carrot",
    (90, 57): "a photo of a person smelling a carrot",
    (97, 57): "a photo of a person stirring a carrot",
    (112, 57): "a photo of a person washing a carrot",
    (58, 57): "a photo of a person and a carrot",
    (9, 77): "a photo of a person carrying a cell phone",
    (37, 77): "a photo of a person holding a cell phone",
    (74, 77): "a photo of a person reading a cell phone",
    (76, 77): "a photo of a person repairing a cell phone",
    (102, 77): "a photo of a person talking on a cell phone",
    (104, 77): "a photo of a person texting on a cell phone",
    (58, 77): "a photo of a person and a cell phone",
    (12, 85): "a photo of a person checking a clock",
    (37, 85): "a photo of a person holding a clock",
    (76, 85): "a photo of a person repairing a clock",
    (83, 85): "a photo of a person setting a clock",
    (58, 85): "a photo of a person and a clock",
    (9, 47): "a photo of a person carrying a cup",
    (21, 47): "a photo of a person drinking with a cup",
    (37, 47): "a photo of a person holding a cup",
    (42, 47): "a photo of a person inspecting a cup",
    (70, 47): "a photo of a person pouring a cup",
    (86, 47): "a photo of a person sipping a cup",
    (90, 47): "a photo of a person smelling a cup",
    (28, 47): "a photo of a person filling a cup",
    (112, 47): "a photo of a person washing a cup",
    (58, 47): "a photo of a person and a cup",
    (8, 60): "a photo of a person buying a donut",
    (9, 60): "a photo of a person carrying a donut",
    (24, 60): "a photo of a person eating a donut",
    (37, 60): "a photo of a person holding a donut",
    (55, 60): "a photo of a person making a donut",
    (68, 60): "a photo of a person picking up a donut",
    (90, 60): "a photo of a person smelling a donut",
    (58, 60): "a photo of a person and a donut",
    (27, 22): "a photo of a person feeding an elephant",
    (37, 22): "a photo of a person holding an elephant",
    (39, 22): "a photo of a person hosing an elephant",
    (40, 22): "a photo of a person hugging an elephant",
    (46, 22): "a photo of a person kissing an elephant",
    (38, 22): "a photo of a person hopping on an elephant",
    (66, 22): "a photo of a person petting an elephant",
    (77, 22): "a photo of a person riding an elephant",
    (111, 22): "a photo of a person walking an elephant",
    (112, 22): "a photo of a person washing an elephant",
    (113, 22): "a photo of a person watching an elephant",
    (58, 22): "a photo of a person and an elephant",
    (40, 11): "a photo of a person hugging a fire hydrant",
    (42, 11): "a photo of a person inspecting a fire hydrant",
    (59, 11): "a photo of a person opening a fire hydrant",
    (62, 11): "a photo of a person painting a fire hydrant",
    (58, 11): "a photo of a person and a fire hydrant",
    (37, 48): "a photo of a person holding a fork",
    (51, 48): "a photo of a person lifting a fork",
    (96, 48): "a photo of a person sticking a fork",
    (49, 48): "a photo of a person licking a fork",
    (112, 48): "a photo of a person washing a fork",
    (58, 48): "a photo of a person and a fork",
    (3, 34): "a photo of a person blocking a frisbee",
    (10, 34): "a photo of a person catching a frisbee",
    (37, 34): "a photo of a person holding a frisbee",
    (91, 34): "a photo of a person spinning a frisbee",
    (105, 34): "a photo of a person throwing a frisbee",
    (58, 34): "a photo of a person and a frisbee",
    (27, 25): "a photo of a person feeding a giraffe",
    (46, 25): "a photo of a person kissing a giraffe",
    (66, 25): "a photo of a person petting a giraffe",
    (77, 25): "a photo of a person riding a giraffe",
    (113, 25): "a photo of a person watching a giraffe",
    (58, 25): "a photo of a person and a giraffe",
    (37, 89): "a photo of a person holding a hair drier",
    (60, 89): "a photo of a person operating a hair drier",
    (76, 89): "a photo of a person repairing a hair drier",
    (58, 89): "a photo of a person and a hair drier",
    (9, 31): "a photo of a person carrying a handbag",
    (37, 31): "a photo of a person holding a handbag",
    (42, 31): "a photo of a person inspecting a handbag",
    (58, 31): "a photo of a person and a handbag",
    (9, 58): "a photo of a person carrying a hot dog",
    (15, 58): "a photo of a person cooking a hot dog",
    (16, 58): "a photo of a person cutting a hot dog",
    (24, 58): "a photo of a person eating a hot dog",
    (37, 58): "a photo of a person holding a hot dog",
    (55, 58): "a photo of a person making a hot dog",
    (58, 58): "a photo of a person and a hot dog",
    (9, 76): "a photo of a person carrying a keyboard",
    (13, 76): "a photo of a person cleaning a keyboard",
    (37, 76): "a photo of a person holding a keyboard",
    (110, 76): "a photo of a person typing on a keyboard",
    (58, 76): "a photo of a person and a keyboard",
    (2, 38): "a photo of a person assembling a kite",
    (9, 38): "a photo of a person carrying a kite",
    (31, 38): "a photo of a person flying a kite",
    (37, 38): "a photo of a person holding a kite",
    (42, 38): "a photo of a person inspecting a kite",
    (48, 38): "a photo of a person launching a kite",
    (71, 38): "a photo of a person pulling a kite",
    (58, 38): "a photo of a person and a kite",
    (17, 49): "a photo of a person cutting with a knife",
    (37, 49): "a photo of a person holding a knife",
    (96, 49): "a photo of a person sticking a knife",
    (112, 49): "a photo of a person washing a knife",
    (116, 49): "a photo of a person wielding a knife",
    (49, 49): "a photo of a person licking a knife",
    (58, 49): "a photo of a person and a knife",
    (37, 73): "a photo of a person holding a laptop",
    (59, 73): "a photo of a person opening a laptop",
    (74, 73): "a photo of a person reading a laptop",
    (76, 73): "a photo of a person repairing a laptop",
    (110, 73): "a photo of a person typing on a laptop",
    (58, 73): "a photo of a person and a laptop",
    (13, 78): "a photo of a person cleaning a microwave",
    (59, 78): "a photo of a person opening a microwave",
    (60, 78): "a photo of a person operating a microwave",
    (58, 78): "a photo of a person and a microwave",
    (14, 74): "a photo of a person controlling a mouse",
    (37, 74): "a photo of a person holding a mouse",
    (76, 74): "a photo of a person repairing a mouse",
    (58, 74): "a photo of a person and a mouse",
    (8, 55): "a photo of a person buying an orange",
    (16, 55): "a photo of a person cutting an orange",
    (24, 55): "a photo of a person eating an orange",
    (37, 55): "a photo of a person holding an orange",
    (42, 55): "a photo of a person inspecting an orange",
    (65, 55): "a photo of a person peeling an orange",
    (67, 55): "a photo of a person picking an orange",
    (92, 55): "a photo of a person squeezing an orange",
    (112, 55): "a photo of a person washing an orange",
    (58, 55): "a photo of a person and an orange",
    (13, 79): "a photo of a person cleaning an oven",
    (37, 79): "a photo of a person holding an oven",
    (42, 79): "a photo of a person inspecting an oven",
    (59, 79): "a photo of a person opening an oven",
    (76, 79): "a photo of a person repairing an oven",
    (60, 79): "a photo of a person operating an oven",
    (58, 79): "a photo of a person and an oven",
    (12, 14): "a photo of a person checking a parking meter",
    (64, 14): "a photo of a person paying a parking meter",
    (76, 14): "a photo of a person repairing a parking meter",
    (58, 14): "a photo of a person and a parking meter",
    (8, 59): "a photo of a person buying a pizza",
    (9, 59): "a photo of a person carrying a pizza",
    (15, 59): "a photo of a person cooking a pizza",
    (16, 59): "a photo of a person cutting a pizza",
    (24, 59): "a photo of a person eating a pizza",
    (37, 59): "a photo of a person holding a pizza",
    (55, 59): "a photo of a person making a pizza",
    (68, 59): "a photo of a person picking up a pizza",
    (89, 59): "a photo of a person sliding a pizza",
    (90, 59): "a photo of a person smelling a pizza",
    (58, 59): "a photo of a person and a pizza",
    (13, 82): "a photo of a person cleaning a refrigerator",
    (37, 82): "a photo of a person holding a refrigerator",
    (57, 82): "a photo of a person moving a refrigerator",
    (59, 82): "a photo of a person opening a refrigerator",
    (58, 82): "a photo of a person and a refrigerator",
    (37, 75): "a photo of a person holding a remote",
    (69, 75): "a photo of a person pointing a remote",
    (100, 75): "a photo of a person swinging a remote",
    (58, 75): "a photo of a person and a remote",
    (9, 54): "a photo of a person carrying a sandwich",
    (15, 54): "a photo of a person cooking a sandwich",
    (16, 54): "a photo of a person cutting a sandwich",
    (24, 54): "a photo of a person eating a sandwich",
    (37, 54): "a photo of a person holding a sandwich",
    (55, 54): "a photo of a person making a sandwich",
    (58, 54): "a photo of a person and a sandwich",
    (17, 87): "a photo of a person cutting with a scissors",
    (37, 87): "a photo of a person holding a scissors",
    (59, 87): "a photo of a person opening a scissors",
    (58, 87): "a photo of a person and a scissors",
    (13, 81): "a photo of a person cleaning a sink",
    (76, 81): "a photo of a person repairing a sink",
    (112, 81): "a photo of a person washing a sink",
    (58, 81): "a photo of a person and a sink",
    (9, 41): "a photo of a person carrying a skateboard",
    (29, 41): "a photo of a person flipping a skateboard",
    (33, 41): "a photo of a person grinding a skateboard",
    (37, 41): "a photo of a person holding a skateboard",
    (44, 41): "a photo of a person jumping a skateboard",
    (68, 41): "a photo of a person picking up a skateboard",
    (77, 41): "a photo of a person riding a skateboard",
    (88, 41): "a photo of a person sitting on a skateboard",
    (94, 41): "a photo of a person standing on a skateboard",
    (58, 41): "a photo of a person and a skateboard",
    (1, 35): "a photo of a person adjusting a skis",
    (9, 35): "a photo of a person carrying a skis",
    (37, 35): "a photo of a person holding a skis",
    (42, 35): "a photo of a person inspecting a skis",
    (44, 35): "a photo of a person jumping a skis",
    (68, 35): "a photo of a person picking up a skis",
    (76, 35): "a photo of a person repairing a skis",
    (77, 35): "a photo of a person riding a skis",
    (94, 35): "a photo of a person standing on a skis",
    (115, 35): "a photo of a person wearing a skis",
    (58, 35): "a photo of a person and a skis",
    (1, 36): "a photo of a person adjusting a snowboard",
    (9, 36): "a photo of a person carrying a snowboard",
    (33, 36): "a photo of a person grinding a snowboard",
    (37, 36): "a photo of a person holding a snowboard",
    (44, 36): "a photo of a person jumping a snowboard",
    (77, 36): "a photo of a person riding a snowboard",
    (94, 36): "a photo of a person standing on a snowboard",
    (115, 36): "a photo of a person wearing a snowboard",
    (58, 36): "a photo of a person and a snowboard",
    (37, 50): "a photo of a person holding a spoon",
    (49, 50): "a photo of a person licking a spoon",
    (112, 50): "a photo of a person washing a spoon",
    (86, 50): "a photo of a person sipping a spoon",
    (58, 50): "a photo of a person and a spoon",
    (3, 37): "a photo of a person blocking a sports ball",
    (9, 37): "a photo of a person carrying a sports ball",
    (10, 37): "a photo of a person catching a sports ball",
    (20, 37): "a photo of a person dribbling a sports ball",
    (36, 37): "a photo of a person hitting a sports ball",
    (37, 37): "a photo of a person holding a sports ball",
    (42, 37): "a photo of a person inspecting a sports ball",
    (45, 37): "a photo of a person kicking a sports ball",
    (68, 37): "a photo of a person picking up a sports ball",
    (82, 37): "a photo of a person serving a sports ball",
    (85, 37): "a photo of a person signing a sports ball",
    (91, 37): "a photo of a person spinning a sports ball",
    (105, 37): "a photo of a person throwing a sports ball",
    (58, 37): "a photo of a person and a sports ball",
    (37, 13): "a photo of a person holding a stop sign",
    (95, 13): "a photo of a person standing under a stop sign",
    (98, 13): "a photo of a person stopping at a stop sign",
    (58, 13): "a photo of a person and a stop sign",
    (9, 33): "a photo of a person carrying a suitcase",
    (19, 33): "a photo of a person dragging a suitcase",
    (37, 33): "a photo of a person holding a suitcase",
    (40, 33): "a photo of a person hugging a suitcase",
    (53, 33): "a photo of a person loading a suitcase",
    (59, 33): "a photo of a person opening a suitcase",
    (61, 33): "a photo of a person packing a suitcase",
    (68, 33): "a photo of a person picking up a suitcase",
    (117, 33): "a photo of a person zipping a suitcase",
    (58, 33): "a photo of a person and a suitcase",
    (9, 42): "a photo of a person carrying a surfboard",
    (19, 42): "a photo of a person dragging a surfboard",
    (37, 42): "a photo of a person holding a surfboard",
    (42, 42): "a photo of a person inspecting a surfboard",
    (44, 42): "a photo of a person jumping a surfboard",
    (50, 42): "a photo of a person lying on a surfboard",
    (53, 42): "a photo of a person loading a surfboard",
    (77, 42): "a photo of a person riding a surfboard",
    (94, 42): "a photo of a person standing on a surfboard",
    (88, 42): "a photo of a person sitting on a surfboard",
    (112, 42): "a photo of a person washing a surfboard",
    (58, 42): "a photo of a person and a surfboard",
    (9, 88): "a photo of a person carrying a teddy bear",
    (37, 88): "a photo of a person holding a teddy bear",
    (40, 88): "a photo of a person hugging a teddy bear",
    (46, 88): "a photo of a person kissing a teddy bear",
    (58, 88): "a photo of a person and a teddy bear",
    (9, 43): "a photo of a person carrying a tennis racket",
    (37, 43): "a photo of a person holding a tennis racket",
    (42, 43): "a photo of a person inspecting a tennis racket",
    (100, 43): "a photo of a person swinging a tennis racket",
    (58, 43): "a photo of a person and a tennis racket",
    (1, 32): "a photo of a person adjusting a tie",
    (16, 32): "a photo of a person cutting a tie",
    (37, 32): "a photo of a person holding a tie",
    (42, 32): "a photo of a person inspecting a tie",
    (71, 32): "a photo of a person pulling a tie",
    (106, 32): "a photo of a person tying a tie",
    (115, 32): "a photo of a person wearing a tie",
    (58, 32): "a photo of a person and a tie",
    (37, 80): "a photo of a person holding a toaster",
    (60, 80): "a photo of a person operating a toaster",
    (76, 80): "a photo of a person repairing a toaster",
    (58, 80): "a photo of a person and a toaster",
    (13, 70): "a photo of a person cleaning a toilet",
    (30, 70): "a photo of a person flushing a toilet",
    (59, 70): "a photo of a person opening a toilet",
    (76, 70): "a photo of a person repairing a toilet",
    (88, 70): "a photo of a person sitting on a toilet",
    (94, 70): "a photo of a person standing on a toilet",
    (112, 70): "a photo of a person washing a toilet",
    (58, 70): "a photo of a person and a toilet",
    (7, 90): "a photo of a person brushing with a toothbrush",
    (37, 90): "a photo of a person holding a toothbrush",
    (112, 90): "a photo of a person washing a toothbrush",
    (58, 90): "a photo of a person and a toothbrush",
    (43, 10): "a photo of a person installing a traffic light",
    (76, 10): "a photo of a person repairing a traffic light",
    (95, 10): "a photo of a person standing under a traffic light",
    (98, 10): "a photo of a person stopping at a traffic light",
    (58, 10): "a photo of a person and a traffic light",
    (18, 8): "a photo of a person directing a truck",
    (22, 8): "a photo of a person driving a truck",
    (42, 8): "a photo of a person inspecting a truck",
    (53, 8): "a photo of a person loading a truck",
    (76, 8): "a photo of a person repairing a truck",
    (77, 8): "a photo of a person riding a truck",
    (88, 8): "a photo of a person sitting on a truck",
    (112, 8): "a photo of a person washing a truck",
    (58, 8): "a photo of a person and a truck",
    (9, 28): "a photo of a person carrying a umbrella",
    (37, 28): "a photo of a person holding a umbrella",
    (54, 28): "a photo of a person losing a umbrella",
    (59, 28): "a photo of a person opening a umbrella",
    (76, 28): "a photo of a person repairing a umbrella",
    (83, 28): "a photo of a person setting a umbrella",
    (95, 28): "a photo of a person standing under a umbrella",
    (58, 28): "a photo of a person and a umbrella",
    (37, 86): "a photo of a person holding a vase",
    (55, 86): "a photo of a person making a vase",
    (62, 86): "a photo of a person painting a vase",
    (58, 86): "a photo of a person and a vase",
    (28, 46): "a photo of a person filling a wine glass",
    (37, 46): "a photo of a person holding a wine glass",
    (86, 46): "a photo of a person sipping a wine glass",
    (107, 46): "a photo of a person toasting a wine glass",
    (49, 46): "a photo of a person licking a wine glass",
    (112, 46): "a photo of a person washing a wine glass",
    (58, 46): "a photo of a person and a wine glass",
    (27, 24): "a photo of a person feeding a zebra",
    (37, 24): "a photo of a person holding a zebra",
    (66, 24): "a photo of a person petting a zebra",
    (113, 24): "a photo of a person watching a zebra",
    (58, 24): "a photo of a person and a zebra",
}

hico_obj_text_label = [
    (0, "a photo of a person"),
    (1, "a photo of a bicycle"),
    (2, "a photo of a car"),
    (3, "a photo of a motorcycle"),
    (4, "a photo of an airplane"),
    (5, "a photo of a bus"),
    (6, "a photo of a train"),
    (7, "a photo of a truck"),
    (8, "a photo of a boat"),
    (9, "a photo of a traffic light"),
    (10, "a photo of a fire hydrant"),
    (11, "a photo of a stop sign"),
    (12, "a photo of a parking meter"),
    (13, "a photo of a bench"),
    (14, "a photo of a bird"),
    (15, "a photo of a cat"),
    (16, "a photo of a dog"),
    (17, "a photo of a horse"),
    (18, "a photo of a sheep"),
    (19, "a photo of a cow"),
    (20, "a photo of an elephant"),
    (21, "a photo of a bear"),
    (22, "a photo of a zebra"),
    (23, "a photo of a giraffe"),
    (24, "a photo of a backpack"),
    (25, "a photo of a umbrella"),
    (26, "a photo of a handbag"),
    (27, "a photo of a tie"),
    (28, "a photo of a suitcase"),
    (29, "a photo of a frisbee"),
    (30, "a photo of a skis"),
    (31, "a photo of a snowboard"),
    (32, "a photo of a sports ball"),
    (33, "a photo of a kite"),
    (34, "a photo of a baseball bat"),
    (35, "a photo of a baseball glove"),
    (36, "a photo of a skateboard"),
    (37, "a photo of a surfboard"),
    (38, "a photo of a tennis racket"),
    (39, "a photo of a bottle"),
    (40, "a photo of a wine glass"),
    (41, "a photo of a cup"),
    (42, "a photo of a fork"),
    (43, "a photo of a knife"),
    (44, "a photo of a spoon"),
    (45, "a photo of a bowl"),
    (46, "a photo of a banana"),
    (47, "a photo of an apple"),
    (48, "a photo of a sandwich"),
    (49, "a photo of an orange"),
    (50, "a photo of a broccoli"),
    (51, "a photo of a carrot"),
    (52, "a photo of a hot dog"),
    (53, "a photo of a pizza"),
    (54, "a photo of a donut"),
    (55, "a photo of a cake"),
    (56, "a photo of a chair"),
    (57, "a photo of a couch"),
    (58, "a photo of a potted plant"),
    (59, "a photo of a bed"),
    (60, "a photo of a dining table"),
    (61, "a photo of a toilet"),
    (62, "a photo of a tv"),
    (63, "a photo of a laptop"),
    (64, "a photo of a mouse"),
    (65, "a photo of a remote"),
    (66, "a photo of a keyboard"),
    (67, "a photo of a cell phone"),
    (68, "a photo of a microwave"),
    (69, "a photo of an oven"),
    (70, "a photo of a toaster"),
    (71, "a photo of a sink"),
    (72, "a photo of a refrigerator"),
    (73, "a photo of a book"),
    (74, "a photo of a clock"),
    (75, "a photo of a vase"),
    (76, "a photo of a scissors"),
    (77, "a photo of a teddy bear"),
    (78, "a photo of a hair drier"),
    (79, "a photo of a toothbrush"),
    (80, "a photo of nothing"),
]

hico_unseen_index = {
    "default": [],
    # start from 0
    "rare_first": [
        509,
        279,
        280,
        402,
        504,
        286,
        499,
        498,
        289,
        485,
        303,
        311,
        325,
        439,
        351,
        358,
        66,
        427,
        379,
        418,
        70,
        416,
        389,
        90,
        395,
        76,
        397,
        84,
        135,
        262,
        401,
        592,
        560,
        586,
        548,
        593,
        526,
        181,
        257,
        539,
        535,
        260,
        596,
        345,
        189,
        205,
        206,
        429,
        179,
        350,
        405,
        522,
        449,
        261,
        255,
        546,
        547,
        44,
        22,
        334,
        599,
        239,
        315,
        317,
        229,
        158,
        195,
        238,
        364,
        222,
        281,
        149,
        399,
        83,
        127,
        254,
        398,
        403,
        555,
        552,
        520,
        531,
        440,
        436,
        482,
        274,
        8,
        188,
        216,
        597,
        77,
        407,
        556,
        469,
        474,
        107,
        390,
        410,
        27,
        381,
        463,
        99,
        184,
        100,
        292,
        517,
        80,
        333,
        62,
        354,
        104,
        55,
        50,
        198,
        168,
        391,
        192,
        595,
        136,
        581,
    ],  # 120
    "non_rare_first": [
        38,
        41,
        20,
        18,
        245,
        11,
        19,
        154,
        459,
        42,
        155,
        139,
        60,
        461,
        577,
        153,
        582,
        89,
        141,
        576,
        75,
        212,
        472,
        61,
        457,
        146,
        208,
        94,
        471,
        131,
        248,
        544,
        515,
        566,
        370,
        481,
        226,
        250,
        470,
        323,
        169,
        480,
        479,
        230,
        385,
        73,
        159,
        190,
        377,
        176,
        249,
        371,
        284,
        48,
        583,
        53,
        162,
        140,
        185,
        106,
        294,
        56,
        320,
        152,
        374,
        338,
        29,
        594,
        346,
        456,
        589,
        45,
        23,
        67,
        478,
        223,
        493,
        228,
        240,
        215,
        91,
        115,
        337,
        559,
        7,
        218,
        518,
        297,
        191,
        266,
        304,
        6,
        572,
        529,
        312,
        9,
        308,
        417,
        197,
        193,
        163,
        455,
        25,
        54,
        575,
        446,
        387,
        483,
        534,
        340,
        508,
        110,
        329,
        246,
        173,
        506,
        383,
        93,
        516,
        64,
    ],  # 120
    "unseen_object": [
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        224,
        225,
        226,
        227,
        228,
        229,
        230,
        231,
        290,
        291,
        292,
        293,
        294,
        313,
        314,
        315,
        316,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        336,
        337,
        338,
        339,
        340,
        341,
        418,
        419,
        420,
        421,
        422,
        423,
        424,
        425,
        426,
        427,
        428,
        429,
        430,
        431,
        432,
        433,
        453,
        454,
        455,
        456,
        457,
        458,
        459,
        460,
        461,
        462,
        463,
        464,
        465,
        466,
        467,
        468,
        469,
        470,
        471,
        472,
        473,
        533,
        534,
        535,
        536,
        537,
        558,
        559,
        560,
        561,
        595,
        596,
        597,
        598,
        599,
    ],  # 100
    "unseen_verb": [
        4,
        6,
        12,
        15,
        18,
        25,
        34,
        38,
        40,
        49,
        58,
        60,
        68,
        69,
        72,
        73,
        77,
        82,
        96,
        97,
        104,
        113,
        116,
        118,
        122,
        129,
        139,
        147,
        150,
        153,
        165,
        166,
        172,
        175,
        176,
        181,
        190,
        202,
        210,
        212,
        219,
        227,
        228,
        233,
        235,
        243,
        298,
        313,
        315,
        320,
        326,
        336,
        342,
        345,
        354,
        372,
        401,
        404,
        409,
        431,
        436,
        459,
        466,
        470,
        472,
        479,
        481,
        488,
        491,
        494,
        498,
        504,
        519,
        523,
        535,
        536,
        541,
        544,
        562,
        565,
        569,
        572,
        591,
        595,
    ],
    # 84, 20 unseen verbs: [41, 100, 99, 91, 34, 42, 97, 84, 26, 106, 38, 56, 92, 79, 19, 76, 80, 2, 114, 62]
}
